name: MobileMoney Build and Deployment Workflow
on: [push]
jobs:
  nmap-scan:
    runs-on: ubuntu-latest
    #needs: deployment
    steps:
      - name: Updated Packages
        run: sudo apt-get update
      
      - name: Install Nmap
        run: sudo apt-get install nmap -y

      - name: Scan the Domain
        run: nmap ${{ secrets.SURGE_DOMAIN }} -oX nmap-output.xml

      - name: Upload the Scan Report
        uses: actions/upload-artifact@v2
        with:
          name: nmap-results
          path: nmap-output.xml
        if: always()    

